-- Create domains for common data types
CREATE DOMAIN DM_BOOL AS CHAR(1) CHECK (VALUE IN ('T', 'F'));
CREATE DOMAIN DM_EMAIL AS VARCHAR(100);
CREATE DOMAIN DM_PHONE AS VARCHAR(20);
CREATE DOMAIN DM_CURRENCY AS DECIMAL(15,2);
CREATE DOMAIN DM_POSITIVE_INT AS INTEGER CHECK (VALUE > 0);