-- Complex procedure with business logic
CREATE OR ALTER PROCEDURE PROCESS_MONTHLY_SALARY (
    P_MONTH INTEGER,
    P_YEAR INTEGER
)
RETURNS (
    EMP_ID INTEGER,
    EMP_NAME VARCHAR(101),
    MONTHLY_SALARY DM_CURRENCY,
    BONUS DM_CURRENCY,
    TOTAL DM_CURRENCY
)
AS
DECLARE VARIABLE V_BASE_SALARY DM_CURRENCY;
DECLARE VARIABLE V_BONUS_PERCENT DECIMAL(5,2);
BEGIN
    FOR SELECT 
        E.EMP_ID,
        E.FIRST_NAME || ' ' || E.LAST_NAME,
        E.SALARY
    FROM EMPLOYEES E
    WHERE E.HIRE_DATE <= CAST(:P_MONTH || '/1/' || :P_YEAR AS DATE)
    INTO :EMP_ID, :EMP_NAME, :V_BASE_SALARY
    DO
    BEGIN
        -- Calculate bonus (example: 10% for employees hired more than 5 years ago)
        V_BONUS_PERCENT = 0.00;
        IF (EXTRACT(YEAR FROM CURRENT_DATE) - EXTRACT(YEAR FROM E.HIRE_DATE) > 5) THEN
            V_BONUS_PERCENT = 0.10;
        
        BONUS = V_BASE_SALARY * V_BONUS_PERCENT;
        MONTHLY_SALARY = V_BASE_SALARY;
        TOTAL = MONTHLY_SALARY + BONUS;
        
        SUSPEND;
    END
END;