-- Create initial tables
CREATE TABLE USERS (
    USER_ID INTEGER NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL DM_EMAIL,
    IS_ACTIVE DM_BOOL DEFAULT 'T',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DEPARTMENTS (
    DEPT_ID INTEGER NOT NULL PRIMARY KEY,
    DEPT_NAME VARCHAR(100) NOT NULL,
    MANAGER_ID INTEGER,
    BUDGET DM_CURRENCY
);