-- More tables with foreign keys
CREATE TABLE EMPLOYEES (
    EMP_ID INTEGER NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DEPT_ID INTEGER,
    SALARY DM_CURRENCY,
    HIRE_DATE DATE,
    CONSTRAINT FK_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);

CREATE TABLE PROJECTS (
    PROJECT_ID INTEGER NOT NULL PRIMARY KEY,
    PROJECT_NAME VARCHAR(100) NOT NULL,
    BUDGET DM_CURRENCY,
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR(20) DEFAULT 'PLANNED'
);