-- Simple procedures
CREATE OR ALTER PROCEDURE GET_USER_COUNT
RETURNS (USER_COUNT INTEGER)
AS
BEGIN
    SELECT COUNT(*) FROM USERS INTO :USER_COUNT;
    SUSPEND;
END;

CREATE OR ALTER PROCEDURE GET_ACTIVE_USERS
RETURNS (USER_ID INTEGER, USERNAME VARCHAR(50))
AS
BEGIN
    FOR SELECT USER_ID, USERNAME FROM USERS 
    WHERE IS_ACTIVE = 'T'
    INTO :USER_ID, :USERNAME
    DO
    BEGIN
        SUSPEND;
    END
END;