-- Procedure with parameters
CREATE OR ALTER PROCEDURE GET_EMPLOYEES_BY_DEPT (
    P_DEPT_ID INTEGER
)
RETURNS (
    EMP_ID INTEGER,
    FULL_NAME VARCHAR(101),
    SALARY DM_CURRENCY
)
AS
BEGIN
    FOR SELECT 
        E.EMP_ID, 
        E.FIRST_NAME || ' ' || E.LAST_NAME,
        E.SALARY
    FROM EMPLOYEES E
    WHERE E.DEPT_ID = :P_DEPT_ID
    INTO :EMP_ID, :FULL_NAME, :SALARY
    DO
    BEGIN
        SUSPEND;
    END
END;