-- Procedure with calculations
CREATE OR ALTER PROCEDURE CALCULATE_AVG_SALARY
RETURNS (DEPT_ID INTEGER, DEPT_NAME VARCHAR(100), AVG_SALARY DM_CURRENCY)
AS
BEGIN
    FOR SELECT 
        D.DEPT_ID,
        D.DEPT_NAME,
        AVG(E.SALARY)
    FROM DEPARTMENTS D
    LEFT JOIN EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
    GROUP BY D.DEPT_ID, D.DEPT_NAME
    INTO :DEPT_ID, :DEPT_NAME, :AVG_SALARY
    DO
    BEGIN
        SUSPEND;
    END
END;