-- Additional tables
CREATE TABLE TASKS (
    TASK_ID INTEGER NOT NULL PRIMARY KEY,
    TASK_NAME VARCHAR(100) NOT NULL,
    PROJECT_ID INTEGER,
    ASSIGNED_TO INTEGER,
    DUE_DATE DATE,
    COMPLETED DM_BOOL DEFAULT 'F',
    CONSTRAINT FK_TASK_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_TASK_EMPLOYEE FOREIGN KEY (ASSIGNED_TO) REFERENCES EMPLOYEES(EMP_ID)
);

CREATE TABLE SALARY_HISTORY (
    HISTORY_ID INTEGER NOT NULL PRIMARY KEY,
    EMP_ID INTEGER NOT NULL,
    OLD_SALARY DM_CURRENCY,
    NEW_SALARY DM_CURRENCY,
    CHANGE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SALARY_EMP FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);