-- Update and insert procedures
CREATE OR ALTER PROCEDURE UPDATE_EMPLOYEE_SALARY (
    P_EMP_ID INTEGER,
    P_NEW_SALARY DM_CURRENCY
)
AS
BEGIN
    UPDATE EMPLOYEES 
    SET SALARY = :P_NEW_SALARY
    WHERE EMP_ID = :P_EMP_ID;
END;

CREATE OR ALTER PROCEDURE ADD_DEPARTMENT (
    P_DEPT_NAME VARCHAR(100),
    P_MANAGER_ID INTEGER
)
RETURNS (NEW_DEPT_ID INTEGER)
AS
BEGIN
    NEW_DEPT_ID = GEN_ID(DEPT_GEN, 1);
    INSERT INTO DEPARTMENTS (DEPT_ID, DEPT_NAME, MANAGER_ID)
    VALUES (:NEW_DEPT_ID, :P_DEPT_NAME, :P_MANAGER_ID);
END;