-- Create generators (sequences) for auto-increment
CREATE GENERATOR USER_GEN;
SET GENERATOR USER_GEN TO 1000;

CREATE GENERATOR EMP_GEN;
SET GENERATOR EMP_GEN TO 100;

CREATE GENERATOR DEPT_GEN;
SET GENERATOR DEPT_GEN TO 10;

CREATE GENERATOR PROJECT_GEN;
SET GENERATOR PROJECT_GEN TO 50;